### ISSUE TITLE
HTML/CSS

### ISSUE THREAD

**Issue by incrementcenter** [incrementcenter/TT#1]
Ստեղծել առաջին էջի HTML/CSS-ը

**Comment by incrementcenter** [comment]
https://codepen.io/TyStelmach/full/yNxMeJ/

**Comment by Tatevik-Dabaghyan** [comment]
Achqis sxal em arel. im compi mej zroyic fayl em stexcel u dra vra arel html css

**Comment by Tik77** [comment]
isk ura im task-@?
